# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly
env:
  matrix:
    - JULIA_NUM_THREADS=1
    - JULIA_NUM_THREADS=2

codecov: true
coeveralls: true

git:
  depth: 999999
notifications:
  email: false

after_success:
 - julia --color=yes -e 'using Pkg, LombScargle; Pkg.add("PyCall"); Pkg.add("Conda"); using Conda; Conda.add("astropy"); include(joinpath(dirname(pathof(LombScargle)), "..", "test", "astropy.jl"))'

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
